### DISCUSSION TITLE
Duplicate workflow runs when creating an Issue

### DISCUSSION THREAD

**Discussion by tkalve** [danhellem/github-actions-issue-to-work-item#122] [Q&A]
I keep getting multiple workflow runs when I create a new issue, at least one for `opened`, one for `labeled`, one for `assigned` and they run simultaneously. Sometimes (quite often) this results in multiple Tasks in Azure Boards.

Any idea how I can prevent duplicates?

This is my workflow file:
```
name: Azure boards

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]
      
jobs:
  sync-to-azure-boards:
    name: Sync issue to Azure Boards
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.AZBOARDS_DEVOPS_PAT }}"
          github_token: "${{ secrets.ADDTOPROJECTPAT }}" 
          ado_organization: "company"
          ado_project: "project"
          ado_area_path: "project"
          ado_iteration_path: "project\\Sprint 7"
          ado_wit: "Task"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
```

![Workflow runs](https://user-images.githubusercontent.com/123207/208870277-6dc0ceed-8bdb-42f9-ab0a-884e592fc090.png)

![Multiple Azure Board tasks](https://user-images.githubusercontent.com/123207/208870388-7c2d000d-cacf-4ad2-b436-92a81b5923ab.png)
