### ISSUE TITLE
AzDO work item will be created for a comment on a pull request

### ISSUE THREAD

**Issue by dixonjoel** [danhellem/github-actions-issue-to-work-item#126]
With the example .yml file, a comment on a pull request will trigger a new work item to be created.

Per the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only), the 'issue_comment' event fires on issues and pull requests.

Workaround:
Put this 'if' statement in the 'alert' clause
```
jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    steps: ...
```

[AB#21456](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/21456)
