### ISSUE TITLE
Add support for managed identities & service principals

### ISSUE THREAD

**Issue by AaronCrawfis** [danhellem/github-actions-issue-to-work-item#142]
With the addition of [managed identities and service principals](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops) to Azure DevOps, users can now use a service principal to auth to Azure DevOps instead of a PAT.

Today the sync tool only appears to support PATs: https://github.com/danhellem/github-actions-issue-to-work-item/blob/master/index.js#L496

Bearer token support is needed in addition to PATs. The azure-devops-node-api library has a function for this: https://github.com/microsoft/azure-devops-node-api/blob/master/api/WebApi.ts#L72, where it can automatically switch between PATs and bearer tokens. I think a switch to this would allow for PATs.

## Example workflow

Here's an example workflow of what I'm hoping to do:

```
jobs:
  ado:
    name: Sync issue to Azure DevOps
    runs-on: ubuntu-latest
    environment:
      name: issues
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_SP_DEVOPS_SYNC_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_SP_DEVOPS_SYNC_TENANT_ID }}
          allow-no-subscriptions: true
      - name: Get Azure DevOps token
        id: get_ado_token
        run:
          # The resource ID for Azure DevOps is always 499b84ac-1321-427f-aa17-267ca6975798
          # https://learn.microsoft.com/azure/devops/integrate/get-started/authentication/service-principal-managed-identity
          accessToken=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv)
          echo "ADO_TOKEN=$accessToken" >> $GITHUB_ENV
      - name: Print length of ADO_TOKEN
        run: |
          echo "ADO_TOKEN length: ${#ADO_TOKEN}"
      - name: Sync issue to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@v2.2
        env:
          ado_token: ${{ env.ADO_TOKEN }}
          github_token: *****
          ado_organization: *****
          ado_project: *****
          ado_area_path: ******
          ado_iteration_path: *****
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
```
