### ISSUE TITLE
Struggling to config

### ISSUE THREAD

**Issue by SpookySystems** [danhellem/github-actions-issue-to-work-item#28]
Hi all, 
Can someone help me to configure this but keep getting _Failed request: (401)_ please. 
I have given the full access to the token and selected all organizations. Still I'm hitting with above error. 

Below is my work flow file: 

```
name: Sync issue to Azure DevOps work item

"on":
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
    
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "_MyOrganizationName_"
          ado_project: "_MyProjectName_"
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_close_state: "Done"

```

 

[AB#5270](https://dev.azure.com/danhellem/9e4ade6f-32de-4a10-9926-8821c4d1673a/_workitems/edit/5270)
