### ISSUE TITLE
TypeError with New Issue, but Item is created in Azure DevOps

### ISSUE THREAD

**Issue by amenocal** [danhellem/github-actions-issue-to-work-item#59]
I tried to look for the answer in previous issues. The closest one was #41, but it wasn't exactly the same.

I am able to trigger the action, and it creates the item in my backlog. However, when issues is opened the actions fails with the  logs below. However, if I close the issue or edit it, the actions runs perfectly fine and doesn't fail.

Error Logs:
```
Set values from payload & env
Check to see if work item already exists
No work item found, creating work item from issue
(node:2894) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:27:5)
    at error (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:127:15)
    at Object.setFailed (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:101:5)
    at main (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:116:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is is how I have it setup:
```
# This is a basic workflow to help you get started with Actions

name:  Issues-to-work-item

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "myOrg"
          ado_project: "myProj"
          ado_area_path: "OrgName\\ProjectName\\MyTeam"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Done"
          ado_bypassrules: true

```

[AB#430](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/430)
