### ISSUE TITLE
RequestError [HttpError]: Bad credentials, TypeError: (s || "").replace is not a function

### ISSUE THREAD

**Issue by matmaly** [danhellem/github-actions-issue-to-work-item#93]
I'm getting the following error:

```
Run danhellem/github-actions-issue-to-work-item@master
Set values from payload & env
Check to see if work item already exists
No work item found, creating work item from issue
Updating issue body text with AB# syntax
Error in catch statement:
RequestError [HttpError]: Bad credentials
    at /home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async updateIssueBody (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:613:18)
    at async main (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:84:38) {
  name: 'HttpError',
  status: 401,
(node:1729239) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 09 Jul 2021 07:38:27 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    at escapeData (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:66:10)
    server: 'GitHub.com',
    at Command.toString (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:60:35)
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    at issueCommand (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:23:30)
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    at Object.issue (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:27:5)
    'x-content-type-options': 'nosniff',
    at error (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:127:15)
    'x-frame-options': 'deny',
    at Object.setFailed (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:101:5)
    'x-github-media-type': 'github.v3; format=json',
    at main (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:138:10)
    'x-github-request-id': 'EE75:02AD:3AE8884:7030F4B:60E7FCF3',
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    'x-ratelimit-limit': '60',
(node:1729239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

This only happens with new issues, Once the issue is synced it works fine:
![image](https://user-images.githubusercontent.com/15313205/125042658-62aca880-e09a-11eb-9642-68d24bfbde7b.png)

I have write permissions on Github and Read & Write on Work Items on ADO.

This is my config:
```
name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment: 
    types: [created, edited, deleted]

jobs:
  alert:
    runs-on: self-hosted
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "smart-azure"
          ado_project: "smart-aws"
          ado_area_path: "smart-aws\\Day-To-Day Tasks"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Done"
          ado_bypassrules: true
          log_level: 100
```

[AB#735](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/735)
